apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.servicebackend.serviceName . }}
  namespace: {{ tpl .Values.servicebackend.namespace . }}
spec:
  selector:
    app: {{ tpl .Values.servicebackend.appName . }}
  ports:
    - port: {{ .Values.servicebackend.port }}
      targetPort: {{ .Values.servicebackend.containerPort }}
  type: ClusterIP
