//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Title")
export class TitleEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Id: string;


}
