apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl .Values.servicefrontend.ingressName . }}
  namespace: {{ tpl .Values.servicefrontend.namespace . }}
  annotations:
    kubernetes.io/ingress.class: "public"
    #nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: lets-encrypt
    #nginx.ingress.kubernetes.io/location-snippet: |
    #  location / {
    #    try_files $uri $uri/ /index.html;
    #  }
spec:
  tls:
  - hosts:
    - {{ tpl .Values.servicefrontend.host . }}
    secretName: {{ tpl .Values.servicefrontend.ingressName . }}-tls 
  rules:
  - host: {{ tpl .Values.servicefrontend.host . }}
    http:
      paths:
      - path: /{{ tpl .Values.appName . }} 
        pathType: Prefix
        backend:
          service:
            name: {{ tpl .Values.servicefrontend.serviceName . }}
            port:
              number: {{ .Values.servicefrontend.containerPort }}