apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.servicefrontend.serviceName . }}
  namespace: {{ tpl .Values.servicefrontend.namespace . }}
spec:
  selector:
    app: {{ tpl .Values.servicefrontend.serviceName . }}
  ports:
    - port: {{ .Values.servicefrontend.port }}
      targetPort: {{ .Values.servicefrontend.containerPort }}
  type: ClusterIP